### ISSUE TITLE
No such module 'ZIPFoundation'

### ISSUE THREAD

**Issue by lkalashnikov** [tomkidd/Quake3-iOS#3]
Cant fix it anyhow to run on iphone x (

**Comment by tomkidd** [comment]
I have no idea why GitHub wasn't automatically telling me about these issues being posted. I'm now "watching" the repo so hopefully they start.

Anyway get the latest, I've moved it to Swift Package Manager (requires Xcode 11, I think) and so this issue should fix itself from now on.
